secretGenerator:
- name: mysql-pass
  literals:
  - password=Vishal@1995
resources:
         - wordpress-ingress.yml
         - mysql-pv.yml
         - wordpress-pv.yml
         - mysql-pvc.yml
         - wordpress-pvc.yml
         - mysql-service.yml
         - wordpress-service.yml
         - deploymysql.yml
         - deploy-wordpress.yml
